# -*- coding: utf-8 -*-
"""auth_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dhmo1h-X2bU8lq1OQRUPMbh77x2cveJy
"""

import streamlit as st
import json
import os
import hashlib

USER_FILE = "users.json"

# -----------------------------
# Helper functions
# -----------------------------
def load_users():
    """Load users from JSON file."""
    if os.path.exists(USER_FILE):
        with open(USER_FILE, "r") as f:
            return json.load(f)
    return {}

def save_users(users):
    """Save users dict to JSON file."""
    with open(USER_FILE, "w") as f:
        json.dump(users, f, indent=4)

def hash_password(password: str) -> str:
    """Return SHA256 hash of password."""
    return hashlib.sha256(password.encode()).hexdigest()

# -----------------------------
# Main auth function (like your check_password)
# -----------------------------
def check_password():
    """
    Returns True if user is logged in.
    Shows login / signup UI if not.
    """

    # ---- Initialise session state keys ----
    if "users" not in st.session_state:
        st.session_state["users"] = load_users()
    if "logged_in" not in st.session_state:
        st.session_state["logged_in"] = False
    if "current_user" not in st.session_state:
        st.session_state["current_user"] = None
    if "show_signup" not in st.session_state:
        st.session_state["show_signup"] = False

    users = st.session_state["users"]

    # ---- Already logged in ----
    if st.session_state["logged_in"]:
        return True

    # ---- UI styling (optional) ----
    st.markdown(
        """
        <style>
        .block-container {padding-top: 2rem;}
        </style>
        """,
        unsafe_allow_html=True,
    )

    st.title("🔒 EV Dashboard Login")

    # -----------------------------
    # SIGNUP SCREEN
    # -----------------------------
    if st.session_state["show_signup"]:
        st.subheader("Create a new account")

        new_username = st.text_input("New username")
        new_password = st.text_input("New password", type="password")
        confirm_password = st.text_input("Confirm password", type="password")

        create_btn = st.button("Create account")
        back_btn = st.button("⬅ Back to login")

        if create_btn:
            if not new_username or not new_password:
                st.error("Please enter username and password")
            elif new_username in users:
                st.error("Username already exists")
            elif new_password != confirm_password:
                st.error("Passwords do not match")
            else:
                # Save user
                users[new_username] = hash_password(new_password)
                save_users(users)
                st.session_state["users"] = users
                st.success("✅ Account created! Please log in now.")
                st.session_state["show_signup"] = False
                st.experimental_rerun()

        if back_btn:
            st.session_state["show_signup"] = False
            st.experimental_rerun()

        return False

    # -----------------------------
    # LOGIN SCREEN
    # -----------------------------
    st.subheader("Login")

    username = st.text_input("Username", key="login_username")
    password = st.text_input("Password", type="password", key="login_password")

    login_btn = st.button("Login")
    signup_btn = st.button("Create new account")

    if login_btn:
        if username in users and users[username] == hash_password(password):
            st.session_state["logged_in"] = True
            st.session_state["current_user"] = username
            st.success(f"🎉 Welcome, {username}!")
            st.experimental_rerun()
        else:
            st.error("😕 User not known or password incorrect")

    if signup_btn:
        st.session_state["show_signup"] = True
        st.experimental_rerun()

    return False