# -*- coding: utf-8 -*-
"""backend_signup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dhmo1h-X2bU8lq1OQRUPMbh77x2cveJy
"""

import os
import csv
from flask import Flask, render_template, request, redirect, url_for

app = Flask(__name__)

# Define the name of the CSV file
CSV_FILE = 'users.csv'

@app.route('/', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        # 1. Get data from the HTML form
        username = request.form['username']
        email = request.form['email']
        password = request.form['password']

        # 2. Check if the CSV file exists
        file_exists = os.path.isfile(CSV_FILE)

        # 3. Open the CSV file in 'append' mode ('a')
        try:
            with open(CSV_FILE, mode='a', newline='') as file:
                writer = csv.writer(file)

                # 4. If the file didn't exist, write the header first
                if not file_exists:
                    writer.writerow(['Username', 'Email', 'Password'])

                # 5. Write the user data
                writer.writerow([username, email, password])

            return f"<h1>Success! User {username} added. <a href='/'>Go back</a></h1>"

        except Exception as e:
            return f"An error occurred: {e}"

    # If method is GET, simply show the form
    return render_template('signup.html')

if __name__ == '__main__':
    app.run(debug=True)