# -*- coding: utf-8 -*-
"""Debugging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bk_hWLD57wbggFQIlygJhgZJCEneTrUb
"""

st.sidebar.subheader("Debug: Available Models")
try:
    for m in genai.list_models():
        if 'generateContent' in m.supported_generation_methods:
            st.sidebar.write(m.name)
except Exception as e:
    st.sidebar.error(f"Error: {e}")