# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dhmo1h-X2bU8lq1OQRUPMbh77x2cveJy
"""

import streamlit as st
import hashlib

# 1. Simple User Database (In-Memory for Demo)
# In production, replace this with a database connection
users_db = {
    "nakul": hashlib.sha256("123456".encode()).hexdigest()
}

def check_password(username, password):
    if username in users_db:
        input_hash = hashlib.sha256(password.encode()).hexdigest()
        if input_hash == users_db[username]:
            return True
    return False

# 2. Session State Management
if "authenticated" not in st.session_state:
    st.session_state["authenticated"] = False

# 3. Login UI
def login():
    st.title("Login Page")
    username = st.text_input("Username")
    password = st.text_input("Password", type="password")

    if st.button("Login"):
        if check_password(username, password):
            st.session_state["authenticated"] = True
            st.rerun() # Reload the app to show the main page
        else:
            st.error("Invalid Username or Password")

# 4. Main App UI (Protected)
def main_app():
    st.title("Welcome, Nakul!")
    st.write("You have successfully logged in.")
    st.write("Here is your private dashboard data.")

    if st.button("Logout"):
        st.session_state["authenticated"] = False
        st.rerun()

# 5. Logic Flow
if st.session_state["authenticated"]:
    main_app()
else:
    login()